// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkau7MDMngjMg9IVVOaPAYii23bTGAU4c',
    appId: '1:880055907001:web:2936d5329d2356d74b2168',
    messagingSenderId: '880055907001',
    projectId: 'quizapp-6c30e',
    authDomain: 'quizapp-6c30e.firebaseapp.com',
    storageBucket: 'quizapp-6c30e.firebasestorage.app',
    measurementId: 'G-Y406VX3TFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGYwgJnCptvSSkiz3cxXAw4anRaNOUqiM',
    appId: '1:880055907001:android:f5f954c3e786b3814b2168',
    messagingSenderId: '880055907001',
    projectId: 'quizapp-6c30e',
    storageBucket: 'quizapp-6c30e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELC4rtZ6FhjaottPdlIJqdwIUv1xJ7M0',
    appId: '1:880055907001:ios:6980b81092663bb94b2168',
    messagingSenderId: '880055907001',
    projectId: 'quizapp-6c30e',
    storageBucket: 'quizapp-6c30e.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELC4rtZ6FhjaottPdlIJqdwIUv1xJ7M0',
    appId: '1:880055907001:ios:6980b81092663bb94b2168',
    messagingSenderId: '880055907001',
    projectId: 'quizapp-6c30e',
    storageBucket: 'quizapp-6c30e.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkau7MDMngjMg9IVVOaPAYii23bTGAU4c',
    appId: '1:880055907001:web:c7b386cd0d58b8c24b2168',
    messagingSenderId: '880055907001',
    projectId: 'quizapp-6c30e',
    authDomain: 'quizapp-6c30e.firebaseapp.com',
    storageBucket: 'quizapp-6c30e.firebasestorage.app',
    measurementId: 'G-Z0R0TKN5NT',
  );
}
